config/routes.rb
Armadillo::Application.routes.draw do
  resources :filters, :only => [ :index, :new, :create, :destroy ]
  resources :users, :only => [ :create, :destroy ]
  match '/signup' =>'users#new', :as => :new_user

  resource :session, :only => [ :create ]
  match '/login' => 'sessions#new', :as => :login
  match '/logout' => 'sessions#destroy', :as => :logout

  root :to => 'pages#show', :id => 'home'
end

app/models/filter.rb
class Filter < ActiveRecord::Base
  belongs_to :user

  validates_presence_of :query, :user
end

app/models/session.rb
class Session
  attr_accessor :email, :password

  def initialize(options = nil)
    unless options.nil?
      options.each do |key, value|
        send("#{key}=", value)
      end
    end
  end

  def user
    User.authenticate email, password
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  include Clearance::User

  attr_accessor :confirmation

  validate :confirmation_match

  attr_accessible :email, :password, :confirmation

  has_many :filters

  private

  def confirmation_match
    unless !password.blank? && password == confirmation
      errors[:confirmation] << I18n.translate('user.errors.no_confirmation_match')
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Authentication
  protect_from_forgery

  before_filter :authorize

  private

  def sign_in_url
    login_url
  end
end

app/controllers/filters_controller.rb
class FiltersController < ApplicationController
  def index
    @filters = current_user.filters
  end

  def new
    @filter = current_user.filters.build
  end

  def create
    @filter = current_user.filters.build params[:filter]

    if @filter.save
      flash[:success] = translate('filter.create.success')

      redirect_to filters_path
    else
      flash[:failure] = translate('filter.create.failure')

      render :action => 'new'
    end
  end

  def destroy
    filter.destroy

    flash[:success] = translate('filter.destroy.success')

    redirect_to filters_path
  end

  private

  def filter
    Filter.find params[:id]
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_filter :authorize, :only => [ :show ]

  def show
    render :action => params[:id]
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_filter :authorize, :only => [ :new, :create, :destroy ]

  def new
  end

  def create
    if user = Session.new(params[:session]).user
      sign_in user

      flash[:success] = translate('session.create.success')
      redirect_back_or root_path
    else
      flash[:failure] = translate('session.create.failure')

      render :action => 'new'
    end
  end

  def destroy
    sign_out

    flash[:success] = translate('session.destroy.success')

    redirect_back_or root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_filter :authorize, :only => [ :new, :create ]

  def new
    @user = User.new
  end

  def create
    @user = User.new params[:user]

    if @user.save
      sign_in @user
      flash[:success] = translate('user.create.success')

      redirect_to root_path
    else
      flash[:failure] = translate('user.create.failure')

      render :action => 'new'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/filters/_form.html.erb
<%= form.error_messages %>

<%= form.label :query %>
<%= form.text_field :query %>

<%= form.submit 'filter.create_button' %>

app/views/filters/index.html.erb
<h1><%= t 'filter.list' %></h1>

<ul>
  <% @filters.each do |filter| -%>
    <%= content_tag :li, :id => dom_id(filter) do -%>
      <%= h filter.query %>
      <%= form_for :filter, :url => filter, :html => { :method => :delete } do |f| %>
        <%= f.submit t('filter.destroy_button') %>
      <% end -%>
    <% end -%>
  <% end -%>
</ul>

<%= form_for Filter.new do |f| -%>
  <%= render :partial => 'form', :locals => { :form => f } %>
<% end -%>

app/views/filters/new.html.erb
<h1><%= t 'filter.new' %></h1>

<%= form_for @filter do |f| -%>
  <%= render :partial => 'form', :locals => { :form => f } %>
<% end -%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Armadillo</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

  <ul id="flash">
    <% flash.each do |type, message| -%>
      <%= content_tag :li, h(message), :class => h(type) %>
    <% end -%>
  </ul>

  <ul id="nav">
    <% if signed_in? -%>
      <li><%= link_to t('filter.list'), filters_path %></li>
      <li><%= link_to t('session.destroy_link'), logout_path %></li>
    <% else -%>
      <li><%= link_to t('session.create_link'), login_path %></li>
      <li><%= link_to t('user.create_link'), new_user_path %></li>
    <% end -%>
  </ul>

  <%= yield %>

</body>
</html>

app/views/pages/home.html.erb
<h1>Welcome!</h1>

<p>Not much here, but you can take a look at our <a href="http://github.com/ratnikov/armadillo">code</a>!</p>

app/views/users/new.html.erb
<h1><%= t 'users.new' %></h1>

<%= form_for @user do |form| -%>
  <%= form.error_messages %>

  <%= form.label :email %>
  <%= form.text_field :email %>

  <%= form.label :password %>
  <%= form.password_field :password %>

  <%= form.label :confirmation %>
  <%= form.password_field :confirmation %>


  <%= form.submit t('user.create_button') %>
<% end -%>